Repository honeycombio/beeline-python, pull requests merged in 2021-11, with the labels that each got.

#189 Add example app using Flask
  .gitignore
  examples/flask/README.md
  examples/flask/app.py
  examples/flask/pyproject.toml
Labels: type: documentation, version: no bump

#190 [flask] Close trace regardless of exception
  beeline/middleware/flask/__init__.py
Labels: type: bug, version: bump patch

#191 [flask] fix: Remove condition on status code
  beeline/middleware/flask/__init__.py
Labels: type: bug, version: bump patch

#194 Update dependabot to monthly
  .github/dependabot.yml
Labels: type: maintenance, version: no bump, merge at will
