Repository honeycombio/beeline-python, pull requests merged in 2022-04, with the labels that each got.

#216 Prepare v3.3.1 release
  .bumpversion.cfg
  CHANGELOG.md
  beeline/version.py
  pyproject.toml
Labels: type: maintenance, version: bump patch

#220 docs: using FileTransmission with classic requires 32 character key
  CHANGELOG.md
  README.md
Labels: type: maintenance, version: no bump

#219 Add meta.span_type to root/subroot spans
  beeline/test_trace.py
  beeline/trace.py
Labels: type: enhancement, version: bump minor
