Repository honeycombio/beeline-python, pull requests merged in 2023-01, with the labels that each got.

#257 fix: Parse version number for beeline-python/{VERSION} addition
  beeline/__init__.py
Labels: type: bug, merge at will

#255 fix: Only try to calculate query duration when we have start time
  beeline/middleware/flask/__init__.py
Labels: type: bug, version: bump patch

#258 rel: Prepare v3.5.1 release
  .bumpversion.cfg
  CHANGELOG.md
  beeline/version.py
  pyproject.toml
Labels: type: maintenance, version: bump patch
