Repository honeycombio/beeline-python, pull requests merged in 2024-03, with the labels that each got.

#296 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog

#295 feat: add Classic Ingest Key support
  beeline/__init__.py
  poetry.lock
  pyproject.toml
Labels: type: enhancement, version: bump minor

#297 rel: v3.6.0
  .bumpversion.cfg
  CHANGELOG.md
  beeline/version.py
  pyproject.toml
Labels: no-changelog
